export {default as Header} from './main/Header'
export {default as WeddingEvent} from './main/WeddingEvent'
export {default as WeddingFormat} from './main/WeddingFormat'
export {default as WeddingBanner} from './main/WeddingBanner'
export {default as WeddingCount} from './main/WeddingCount'
export {default as WeddingAdvert} from './main/WeddingAdvert'